"""
Fetch all 22 chapter HTMLs from the Project-Grendel source repo, extract
prose + inline images + glossary terms, and emit data/chapters.js for the
Dossier prototype.
"""
import json
import re
import sys
import urllib.request

REPO = "https://raw.githubusercontent.com/dknos/Project-Grendel-A-JP4-Fan-WebNovel/HEAD"
CHAPTERS = 22
IMG_PREFIX = "/Project-Grendel-A-JP4-Fan-WebNovel/"
IMG_REPLACEMENT = REPO + "/"

CONTENT_RE = re.compile(
    r'<div id="chapter-content-wrapper"[^>]*>(.*?)</div>\s*\n\s*\n?\s*(?:<!--|<nav|</main)',
    re.DOTALL,
)
TITLE_RE = re.compile(r"<h1>Chapter\s+\d+:\s*(.+?)</h1>")
P_RE = re.compile(r"<p[^>]*>(.*?)</p>", re.DOTALL)
IMG_RE = re.compile(r'<img\s+([^>]+?)/?>')
ATTR_RE = re.compile(r'(\w+)="([^"]*)"')
GLOSS_RE = re.compile(
    r'<span\s+class="glossary-linked-term"\s+data-definition="([^"]*)"\s+data-term="([^"]*)"\s*>([^<]*)</span>',
    re.DOTALL,
)
WS_RE = re.compile(r"\s+")


def fetch(n: int) -> str:
    url = f"{REPO}/chapter-{n:03d}/index.html"
    print(f"  fetching {url}", file=sys.stderr)
    with urllib.request.urlopen(url) as r:
        return r.read().decode("utf-8")


def html_attrs(s: str) -> dict:
    return dict(ATTR_RE.findall(s))


def clean_text(s: str) -> str:
    # Strip residual HTML, preserve <em>/<i>/<br> as plain markers
    s = s.replace("<br/>", " ").replace("<br>", " ").replace("</br>", " ")
    s = re.sub(r"</?(em|i|strong|b|small)\b[^>]*>", "", s)
    s = WS_RE.sub(" ", s).strip()
    # Decode common HTML entities
    s = (
        s.replace("&nbsp;", " ")
        .replace("&amp;", "&")
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", '"')
        .replace("&#39;", "'")
        .replace("&hellip;", "…")
        .replace("&mdash;", "—")
        .replace("&ndash;", "–")
        .replace("&rsquo;", "’")
        .replace("&lsquo;", "‘")
        .replace("&rdquo;", "”")
        .replace("&ldquo;", "“")
    )
    return s


def parse_chapter(n: int, html: str, glossary: dict) -> dict:
    title_m = TITLE_RE.search(html)
    title = title_m.group(1).strip() if title_m else f"Chapter {n}"

    body_m = CONTENT_RE.search(html)
    if not body_m:
        raise RuntimeError(f"chapter {n}: content-wrapper not found")
    body = body_m.group(1)

    blocks = []
    for p in P_RE.finditer(body):
        inner = p.group(1)

        # Image-only paragraph?
        img_m = IMG_RE.search(inner)
        if img_m:
            attrs = html_attrs(img_m.group(1))
            src = attrs.get("src", "")
            if src.startswith(IMG_PREFIX):
                src = IMG_REPLACEMENT + src[len(IMG_PREFIX):]
            blocks.append({
                "type": "fig",
                "src": src,
                "alt": attrs.get("alt", ""),
            })
            # Strip the img and keep any remaining text
            text_remainder = IMG_RE.sub("", inner)
        else:
            text_remainder = inner

        # Replace glossary spans with {{Term}} markers and collect defs
        def gloss_sub(m):
            defn, term, label = m.group(1), m.group(2), m.group(3)
            key = term or label
            if key not in glossary:
                glossary[key] = clean_text(defn)
            return "{{" + (label or term) + "}}"

        text_remainder = GLOSS_RE.sub(gloss_sub, text_remainder)
        text = clean_text(text_remainder)
        if text:
            blocks.append({"type": "p", "text": text})

    return {"n": n, "title": title, "blocks": blocks}


def first_paragraph_as_epigraph(blocks):
    for b in blocks:
        if b["type"] == "p":
            return b["text"]
    return ""


def main():
    print("Fetching 22 chapters from source repo…", file=sys.stderr)
    glossary: dict[str, str] = {}
    chapters = []
    for n in range(1, CHAPTERS + 1):
        html = fetch(n)
        ch = parse_chapter(n, html, glossary)
        chapters.append(ch)

    # Auto-extract a short epigraph: prefer first short italic-ish line; fallback to first sentence
    for ch in chapters:
        first = first_paragraph_as_epigraph(ch["blocks"])
        sentence = re.split(r"(?<=[.!?])\s", first, 1)[0]
        ch["epigraph"] = {
            "text": sentence[:220],
            "attribution": "— Field log, Project Grendel",
        }

    out = {f"NOVEL_CH_FULL": {ch["n"]: ch for ch in chapters}}
    out_glossary = {
        term: {"cat": "term", "def": defn}
        for term, defn in glossary.items()
    }

    js = (
        "// Auto-generated by build_chapters.py — do not edit by hand.\n"
        "// Source: dknos/Project-Grendel-A-JP4-Fan-WebNovel\n\n"
        "window.NOVEL_CH_FULL = "
        + json.dumps({ch["n"]: ch for ch in chapters}, ensure_ascii=False, indent=2)
        + ";\n\n"
        "window.NOVEL_GLOSS_FULL = "
        + json.dumps(out_glossary, ensure_ascii=False, indent=2)
        + ";\n\n"
        "// Back-compat: keep NOVEL_CH for chapter-to-chapter nav, but route through NOVEL_CH_FULL\n"
        "window.NOVEL_CH = window.NOVEL_CH_FULL;\n"
        "window.NOVEL_GLOSS_EXT = Object.assign({}, window.NOVEL_GLOSS_EXT || {}, window.NOVEL_GLOSS_FULL);\n"
    )

    with open("data/chapters.js", "w", encoding="utf-8", newline="\n") as f:
        f.write(js)

    print(
        f"Wrote data/chapters.js — {len(chapters)} chapters, {len(glossary)} glossary terms.",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
